[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = ["python -m pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
